services:
  - type: web
    name: flower-classification-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src